spring.datasource.url=jdbc:postgresql://localhost:5432/twinl_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=true

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

vnpay.tmn-code=DEFYULAS
vnpay.hash-secret=PP11DKZPDTHQT1F0JQG2EA9J0KXRQ5KF
vnpay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=http://localhost:5173/payment/vnpay-return
vnpay.ipn-url=http://localhost:8080/api/payments/vnpay/ipn
vnpay.version=2.1.0
vnpay.command=pay

ghn.base-url=${GHN_BASE_URL:https://dev-online-gateway.ghn.vn/shiip/public-api}
ghn.token=${GHN_TOKEN}
ghn.shop-id=${GHN_SHOP_ID}
ghn.service-type-id=${GHN_SERVICE_TYPE_ID:2}
ghn.payment-type-id=${GHN_PAYMENT_TYPE_ID:1}
ghn.return-address=${GHN_RETURN_ADDRESS:TP HCM}
ghn.return-phone=${GHN_RETURN_PHONE:0900000000}
ghn.return-district-id=${GHN_RETURN_DISTRICT_ID:1454}
ghn.return-ward-code=${GHN_RETURN_WARD_CODE:21207}
ghn.webhook-token=${GHN_WEBHOOK_TOKEN:}