spring.application.name=BE_TWINL
spring.config.import=optional:classpath:application-env.properties

spring.profiles.active=local

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS}

app.cors.allowed-origin=http://localhost:5173

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

gemini.api.key=${GEMINI_API_KEY}
model.gemini=${MODEL_GEMINI}