# Supabase PostgreSQL
DB_HOST=db.fbmtuldepsjgdpwzctzr.supabase.co
DB_PORT=5432
DB_NAME=postgres
DB_USER=postgres
DB_PASSWORD=Twinl14124869

# JWT
JWT_SECRET=9fA7xK2mPqL8vR4tYwZ1nB6cD3sHjU5eG0iT9oXk
JWT_EXPIRATION_MS=86400000

# Cloudinary
CLOUDINARY_CLOUD_NAME=twinl
CLOUDINARY_API_KEY=355535211946391
CLOUDINARY_API_SECRET=-LuTseAn7ZS2q4AMbalc3vyq48w
