# Supabase PostgreSQL
DB_HOST=aws-1-ap-northeast-1.pooler.supabase.com
DB_PORT=6543
DB_NAME=postgres
DB_USER=postgres.nnpggyoafsvyxjpcatag
DB_PASSWORD=Twinl14124869

# JWT
JWT_SECRET=9fA7xK2mPqL8vR4tYwZ1nB6cD3sHjU5eG0iT9oXk
JWT_EXPIRATION_MS=86400000

# Cloudinary
CLOUDINARY_CLOUD_NAME=twinl
CLOUDINARY_API_KEY=355535211946391
CLOUDINARY_API_SECRET=-LuTseAn7ZS2q4AMbalc3vyq48w

# VNPAY
vnpay.tmn-code=DEFYULAS
vnpay.hash-secret=PP11DKZPDTHQT1F0JQG2EA9J0KXRQ5KF
vnpay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=http://localhost:5173/payment/vnpay-return
vnpay.ipn-url=http://localhost:8080/api/payments/vnpay/ipn
vnpay.version=2.1.0
vnpay.command=pay

# Google Gemini API
gemini.api.key=AIzaSyCIqgjr39sk7UiAs7p6cc5jeVu6RV9pqIw
model.gemini=gemini-flash-latest