spring.datasource.url=jdbc:postgresql://localhost:5432/twinl_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=true

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

vnpay.tmn-code=DEFYULAS
vnpay.hash-secret=PP11DKZPDTHQT1F0JQG2EA9J0KXRQ5KF
vnpay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=http://localhost:5173/payment/vnpay-return
vnpay.ipn-url=http://localhost:8080/api/payments/vnpay/ipn
vnpay.version=2.1.0
vnpay.command=pay